# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statics.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import configparser


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(689, 299)
        config = configparser.ConfigParser()
        config.read("config.ini")
        loc = config["locale"]["locale"]
        if loc == "ko_KR":
            fname = "맑은 고딕"
        elif loc == "ja_JP":
            fname = "Meiryo"
        else:
            fname = "malgun gothic"
        font = QtGui.QFont()
        font.setFamily(fname)
        Form.setFont(font)
        self.cbMydeck = QtWidgets.QComboBox(Form)
        self.cbMydeck.setGeometry(QtCore.QRect(45, 30, 111, 22))
        self.cbMydeck.setObjectName("cbMydeck")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(3, 10, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 57, 51, 21))
        font = QtGui.QFont()
        font.setFamily(fname)
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbOppocls = QtWidgets.QComboBox(Form)
        self.cbOppocls.setGeometry(QtCore.QRect(45, 100, 111, 22))
        self.cbOppocls.setObjectName("cbOppocls")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(3, 80, 121, 16))
        self.label_3.setObjectName("label_3")
        self.cbOppodeck = QtWidgets.QComboBox(Form)
        self.cbOppodeck.setGeometry(QtCore.QRect(45, 150, 111, 22))
        self.cbOppodeck.setObjectName("cbOppodeck")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(3, 130, 121, 16))
        self.label_4.setObjectName("label_4")
        self.tablesta = QtWidgets.QTableWidget(Form)
        self.tablesta.setGeometry(QtCore.QRect(0, 180, 161, 115))
        self.tablesta.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tablesta.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tablesta.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablesta.setProperty("showDropIndicator", False)
        self.tablesta.setDragDropOverwriteMode(False)
        self.tablesta.setShowGrid(True)
        self.tablesta.setRowCount(3)
        self.tablesta.setColumnCount(3)
        self.tablesta.setObjectName("tablesta")
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesta.setHorizontalHeaderItem(2, item)
        self.tablesta.horizontalHeader().setDefaultSectionSize(38)
        self.tablesta.horizontalHeader().setHighlightSections(True)
        self.tablesta.horizontalHeader().setSortIndicatorShown(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 10, 501, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.staticLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.staticLayout.setContentsMargins(0, 0, 0, 0)
        self.staticLayout.setObjectName("staticLayout")
        self.lb_result = QtWidgets.QLabel(Form)
        self.lb_result.setGeometry(QtCore.QRect(200, 80, 461, 131))
        font = QtGui.QFont()
        font.setFamily(fname)
        font.setPointSize(55)
        self.lb_result.setFont(font)
        self.lb_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_result.setObjectName("lb_result")
        
        self.setWindowTitle("Statics")
        self.label_2.setText("VS")
        self.lb_result.setText("Result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Form", "내 덱"))
        self.label_3.setText(_translate("Form", "상대 직업"))
        self.label_4.setText(_translate("Form", "상대 덱"))
        item = self.tablesta.verticalHeaderItem(0)
        item.setText(_translate("Form", "선공"))
        item = self.tablesta.verticalHeaderItem(1)
        item.setText(_translate("Form", "후공"))
        item = self.tablesta.verticalHeaderItem(2)
        item.setText(_translate("Form", "합계"))
        item = self.tablesta.horizontalHeaderItem(0)
        item.setText(_translate("Form", "승"))
        item = self.tablesta.horizontalHeaderItem(1)
        item.setText(_translate("Form", "패"))
        item = self.tablesta.horizontalHeaderItem(2)
        item.setText(_translate("Form", "승률"))
